# Generated by Django 3.0.2 on 2022-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PreDes', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Presentaciones',
            },
        ),
    ]
