# Generated by Django 3.0.2 on 2022-10-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_Cabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngCabCod', models.CharField(max_length=50, unique=True, verbose_name='Código del documento de ingreso')),
                ('IngCabFec', models.DateField(verbose_name='Fecha de ingreso')),
                ('IngCabProCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
