# Generated by Django 3.0.2 on 2022-10-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        ('presentaciones', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngDetCan', models.IntegerField(verbose_name='Cantidad')),
                ('IngDetCosUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('IngDetArtNom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo', verbose_name='Artículo ingresado')),
                ('IngDetCabCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.Ingreso_Cabecera', verbose_name='Código de documento de ingreso')),
                ('IngDetPreDes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion', verbose_name='Presentación del artículo')),
            ],
            options={
                'verbose_name_plural': 'Detalle de ingresos de productos',
                'unique_together': {('IngDetCabCod', 'IngDetArtNom')},
            },
        ),
    ]
