# Generated by Django 3.0.2 on 2022-10-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatDes', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
        ),
    ]
