# Generated by Django 3.0.2 on 2022-10-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProNom', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('ProDir', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('ProTel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
